//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recomida.WebApp.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurantes()
        {
            this.Valoracion = new HashSet<Valoracion>();
        }
    
        public int RestauranteID { get; set; }
        public int TipoRestauranteID { get; set; }
        public int TipoComidaID { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
    
        public virtual TipoComida TipoComida { get; set; }
        public virtual TipoRestaurante TipoRestaurante { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valoracion> Valoracion { get; set; }
    }
}
