//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recomida.WebApp.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valoracion
    {
        public int ValoracionID { get; set; }
        public int UserId { get; set; }
        public int RestauranteID { get; set; }
        public int Puntuaje { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Restaurantes Restaurantes { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
